services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "54321:5432"
    networks:
      - postgres
    restart: unless-stopped

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  eureka-server:
    container_name: eureka-server
    image: 073682984246.dkr.ecr.us-east-1.amazonaws.com/amigoscode_eureka-server:1.1
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring

  apigw:
    container_name: apigw
    image: 073682984246.dkr.ecr.us-east-1.amazonaws.com/amigoscode_apigw:1.1
    ports:
      - "7073:7073"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
    networks:
      - spring

  customer:
    container_name: customer
    image: 073682984246.dkr.ecr.us-east-1.amazonaws.com/amigoscode_customer:1.9
    ports:
      - "7070:7070"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - rabbitmq
      - zipkin

  fraud:
    container_name: fraud
    image: 073682984246.dkr.ecr.us-east-1.amazonaws.com/amigoscode_fraud:1.3
    ports:
      - "7071:7071"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - rabbitmq
      - zipkin

  notification:
    container_name: notification
    image: 073682984246.dkr.ecr.us-east-1.amazonaws.com/amigoscode_notification:1.3
    ports:
      - "7074:7074"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - rabbitmq
      - zipkin

networks:
  spring:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: