spring:

  datasource:
    url: jdbc:postgresql://postgres:54321/fraud
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: "http://eureka-server:8761/eureka"
    fetch-registry: true
    register-with-eureka: true
    enabled: false